language: go
go:
  #- 1.x
  - stable
  - tip

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

install:
  - export GO111MODULE=on; go get || go get -t ./...
  - go get golang.org/x/lint/golint
  - go get github.com/gordonklaus/ineffassign
stages:
  - name: lint
    if: env(GIMME_OS) = linux
  - name: test
    if: env(GIMME_OS) = linux
  - name: build
  - name: run
    if: env(GIMME_OS) = linux

jobs:
  include:
  - stage: lint
    script:
      - diff <(echo -n) <(gofmt -s -d .)  # Lint Check - Code Formatting
      - go vet ./...
      - golint ./... || true
  - stage: test
    script:
      - ineffassign .  # Lint Check - Unused assignment
      - make test
  - stage: build
    script:
      - make build
      - make build_binaries
      - cat binaries/sha256sum.txt
  - stage: run
    script:
      - make run
      - ./$(find binaries -name "*.${GIMME_OS}.${GIMME_ARCH}*")
      - ./$(find binaries -name "*.${GIMME_OS}.${GIMME_ARCH}*") -n 6
      - ./$(find binaries -name "*.${GIMME_OS}.${GIMME_ARCH}*") --help || true
