language: go
go:
- 1.11
- 1.x
- release
- tip

install:
- export GO111MODULE=on; go get || go get -t ./...

script:
- make test
- make build
- make run
- make build_binaries
- cat binaries/sha256sum.txt
- ./$(find binaries -name '*.linux.amd64')
- ./$(find binaries -name '*.linux.amd64') -n 6
- ./$(find binaries -name '*.linux.amd64') --help || true
