name: gophrase
version: '0.0.2'
summary: CLI tool to generate easy to remember strong passwords.
description: |
  GoPhrase suggests easy to remember yet strong passwords.

#confinement: devmode
base: core18

parts:
  gophrase:
    plugin: go
    #go-importpath: cmd/gophrase.go
    #source: https://github.com/ylogx/gophrase.git
    source: https://github.com/ylogx/gophrase
    source-type: git
    #go-importpath: .
    #source: .
    build-packages:
      - gcc

apps:
  gophrase:
    command: cmd
